{{- $secretEnabled := false }}
{{- if or .Values.acr.refreshToken .Values.acr.username .Values.acr.password .Values.docker.token .Values.docker.username .Values.docker.password .Values.ecr.accessKeyID .Values.ecr.secretAccessKey .Values.ecr.sessionToken .Values.gcr.token .Values.quay.token .Values.selfhosted.token .Values.selfhosted.username .Values.selfhosted.password }}
{{- $secretEnabled = true }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "version-checker.name" . }}
  labels:
{{ include "version-checker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "version-checker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "version-checker.name" . }}
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        enable.version-checker.io/{{ include "version-checker.name" . }}: "true"
    spec:
      serviceAccountName: {{ include "version-checker.name" . }}
      containers:
      - name: {{ include "version-checker.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        command: ["version-checker"]
        args:
          - "--image-cache-timeout={{.Values.versionChecker.imageCacheTimeout}}"
          - "--log-level={{.Values.versionChecker.logLevel}}"
          - "--metrics-serving-address={{.Values.versionChecker.metricsServingAddress}}"
          - "--test-all-containers={{.Values.versionChecker.testAllContainers}}"
          - "--docker-login-url={{.Values.docker.loginURL}}"
          - "--selfhosted-registry-url={{.Values.selfhosted.URL}}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:

        # ACR
        {{- if .Values.acr.refreshToken }}
        - name: VERSION_CHECKER_ACR_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: acr.refreshToken
        {{- end }}
        {{- if .Values.acr.username }}
        - name: VERSION_CHECKER_ACR_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: acr.username
        {{- end }}
        {{- if .Values.acr.password }}
        - name: VERSION_CHECKER_ACR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: acr.password
        {{- end }}

        # ECR
        {{- if .Values.ecr.accessKeyID }}
        - name: VERSION_CHECKER_ECR_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: ecr.accessKeyID
        {{- end }}
        {{- if .Values.ecr.secretAccessKey }}
        - name: VERSION_CHECKER_ECR_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: ecr.secretAccessKey
        {{- end }}
        {{- if .Values.ecr.sessionToken }}
        - name: VERSION_CHECKER_ECR_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: ecr.sessionToken
        {{- end }}

        # Docker
        {{- if .Values.docker.token }}
        - name: VERSION_CHECKER_DOCKER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: docker.token
        {{- end }}
        {{- if .Values.docker.username }}
        - name: VERSION_CHECKER_DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: docker.username
        {{- end }}
        {{- if .Values.docker.password }}
        - name: VERSION_CHECKER_DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: docker.password
        {{- end }}

        # GCR
        {{- if .Values.gcr.token }}
        - name: VERSION_CHECKER_GCR_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: gcr.token
        {{- end }}

        # Quay
        {{- if .Values.quay.token }}
        - name: VERSION_CHECKER_QUAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: quay.token
        {{- end }}

        # Selfhosted
        {{- if .Values.selfhosted.username }}
        - name: VERSION_CHECKER_SELFHOSTED_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: selfhosted.username
        {{- end }}
        {{- if .Values.selfhosted.password }}
        - name: VERSION_CHECKER_SELFHOSTED_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: selfhosted.password
        {{- end }}
        {{- if .Values.selfhosted.token }}
        - name: VERSION_CHECKER_SELFHOSTED_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "version-checker.name" . }}
              key: selfhosted.token
        {{- end }}

      volumes:
        {{- if $secretEnabled }}
        - name: {{ include "version-checker.name" . }}
          secret:
            secretName: {{ include "version-checker.name" . }}
        {{ end }}

