{{- if or  .Values.docker.token .Values.docker.username .Values.docker.password .Values.gcr.token  .Values.quay.token .Values.acr.refreshToken .Values.acr.username .Values.acr.password }}
apiVersion: v1
data:
  {{- if .Values.docker.token }}
  docker.token: {{.Values.docker.token | b64enc }}
  {{- end}}
  {{- if .Values.docker.username }}
  docker.username: {{.Values.docker.username | b64enc }}
  {{- end}}
  {{- if .Values.docker.password }}
  docker.password: {{.Values.docker.password | b64enc }}
  {{- end}}
  {{- if .Values.acr.refreshToken }}
  acr.refreshToken: {{.Values.acr.refreshToken | b64enc }}
  {{- end}}
  {{- if .Values.acr.username }}
  acr.username: {{.Values.acr.username | b64enc }}
  {{- end}}
  {{- if .Values.acr.password }}
  acr.password: {{.Values.acr.password | b64enc }}
  {{- end}}
  {{- if .Values.gcr.token }}
  gcr.token: {{ .Values.gcr.token | b64enc }}
  {{- end}}
  {{- if .Values.quay.token }}
  quay.token: {{ .Values.quay.token | b64enc }}
  {{- end}}
  {{- if .Values.selfhosted.token }}
  selfhosted.token: {{.Values.selfhosted.token | b64enc }}
  {{- end}}
  {{- if .Values.selfhosted.username }}
  selfhosted.username: {{.Values.selfhosted.username | b64enc }}
  {{- end}}
  {{- if .Values.selfhosted.password }}
  selfhosted.password: {{.Values.selfhosted.password | b64enc }}
  {{- end}}  
kind: Secret
metadata:
  name: {{ include "version-checker.name" . }}
  labels:
{{ include "version-checker.labels" . | indent 4 }}
type: Opaque
{{- end }}
